swagger: '2.0'
info:
  version: '2.0'
  title: Channel Catalogs
  description: |
    This api allows you to manage your channel catalogs. 
    
    A channel catalog is an association between your store and a channel.
    
    You will be able to:
    - map your catalog colums to channel columns.
    - map your catalog categories to the channel categories and define a cost of this category
    - configure the general and cost settings of the channel
    - enable or disable a channel
    - exclude products using filters for a channel
    - override product values for a channel
    - disable or reenable a product on a channel

  contact:
    email: support@beezup.com
  x-logo:
    url: "https://avatars0.githubusercontent.com/u/25665430"
    backgroundColor: "#FFFFFF"
  
  x-changeComment: |
    add product count in channel catalog
    add required properties in channel catalog
    channelCatalogList now returns the channelCatalog instead of channelCatalogHeader.
  
  license:
    name: BeezUP 
    url: http://www.beezup.com

externalDocs: 
  description: BeezUP API documentation
  url: https://beezup.github.io/api-docs/

x-servers:
- url: https://virtserver.swaggerhub.com/BeezUP/user_channelcatalogs/v2
  description: Mock Server
- url: https://api.beezup.com/v2/user/channelCatalogs
  description: Production Server


host: api.beezup.com
basePath: /v2/user/channelCatalogs

x-api-name: V2UserChannelCatalogs
x-api-namespace: BeezUP2.Channel.ApiService 

consumes:
  - application/json
produces:
  - application/json

securityDefinitions:
  api_key:
    description: The api subscription key
    type: apiKey
    name: Ocp-Apim-Subscription-Key
    in: header


security:
- api_key: []


# tags are used for organizing operations
tags:
- name: Global
  description: All global operations
- name: Settings
  description: All settings operations
- name: Column Mappings
  description: All column mapping operations
- name: Category Mappings
  description: All category mapping operations
- name: Exclusion Filters
  description: All exclusion filters operations
- name: Products
  description: All products operations
- name: Products Overrides
  description: All products overrides operations
- name: Products Optimisation
  description: All products optimisation operations

schemes:
 - https


parameters:

  channelCatalogIdParameter:
    name: channelCatalogId
    in: path
    required: true
    description: The channel catalog identifier
    type: string
    format: guid
    x-example: '6d6b04de-406b-4539-8e7e-bf3e8da5dfb0'
    
    
  productIdParameter:
    name: productId
    description: The product identifier
    in: path
    required: true
    type: string
    format: guid
    x-example: '578419df-1bbf-41a6-96fa-862e42182b67'



paths: 
  
  '/':
    get:
      tags:
      - Global
      summary: List all your current channel catalogs 
      operationId: GetChannelCatalogs
      parameters:
      - name: storeId
        in: query
        required: false
        description: The store identifier
        type: string
        format: guid
        x-example: '04730364-9826-4ff3-92e4-51fccd02bf10'
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/channelCatalogList'
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'
    post:
      tags:
      - Global
      summary: Create a new channel catalog
      operationId: CreateChannelCatalog
      parameters:
      - name: request
        in: body
        required: true
        schema:
          $ref: '#/definitions/createChannelCatalogRequest'
      responses:
        201:
          description: When the channel has been successfully added for this store
          headers:
            Location:
              type: string
              description: The new location
              x-example: /v2/user/channelCatalogs/6d6b04de-406b-4539-8e7e-bf3e8da5dfb0
            Retry-After:
              description: The duration in second to wait before polling this resource
              type: integer
              minimum: 5
              default: 5
              x-example: 5
          schema:
            description: Link to the new channel catalog
            type: array
            items:
              $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.Link2'
  
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'
  
  
  
  
  
  '/{channelCatalogId}':
    get:
      tags:
      - Global
      summary: Get the channel catalog information
      operationId: GetChannelCatalog
      parameters:
        - $ref: '#/parameters/channelCatalogIdParameter'
      
      responses:
        200:
          description: Channel catalog
          schema:
            $ref: '#/definitions/channelCatalog'
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'
    delete:
      tags:
      - Global
      summary: Delete the channel catalog
      operationId: DeleteChannelCatalog
      parameters:
        - $ref: '#/parameters/channelCatalogIdParameter'
      responses:
        204:
          description: Channel catalog deleted
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'


  '/{channelCatalogId}/enable':
    post:
      tags:
      - Settings
      summary: Enable a channel catalog
      operationId: EnableChannelCatalog
      parameters:
        - $ref: '#/parameters/channelCatalogIdParameter'
      responses:
        204:
          description: Channel catalog enabled
        402:
          description: You have to upgrade your offer to activate this channel catalog
          schema:
            $ref: '#/definitions/upgradeOfferRequired'
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'
    
  '/{channelCatalogId}/disable':
    post:
      tags:
      - Settings
      summary: Disable a channel catalog
      operationId: DisableChannelCatalog
      parameters:
        - $ref: '#/parameters/channelCatalogIdParameter'
      responses:
        204:
          description: Channel catalog disabled
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'


  '/{channelCatalogId}/settings/general':
    post:
      tags:
      - Settings
      summary: Disable a channel catalog
      operationId: ConfigureChannelCatalogGeneralSettings
      parameters:
        - $ref: '#/parameters/channelCatalogIdParameter'
        - name: request
          in: body
          required: true
          schema:
            $ref: '#/definitions/generalSettings'
      responses:
        204:
          description: Channel catalog general settings configured
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'

  '/{channelCatalogId}/settings/cost':
    post:
      tags:
      - Settings
      summary: Disable a channel catalog
      operationId: ConfigureChannelCatalogCostSettings
      parameters:
        - $ref: '#/parameters/channelCatalogIdParameter'
        - name: request
          in: body
          required: true
          schema:
            $ref: '#/definitions/costSettings'
      responses:
        204:
          description: Channel catalog cost settings configured
          
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'
      
  '/{channelCatalogId}/columnMappings':
    put:
      tags:
      - Column Mappings
      summary: Configure channel catalog column mappings
      operationId: MapChannelCatalogColumns
      parameters:
        - $ref: '#/parameters/channelCatalogIdParameter'
        - name: request
          in: body
          required: true
          schema:
            $ref: '#/definitions/columnMappingList'
      responses:
        204:
          description: Channel catalog column mappings configured

        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'

  '/{channelCatalogId}/categoryMappings':
    get:
      tags:
      - Category Mappings
      summary: Get channel catalog categories
      operationId: GetChannelCatalogCategories
      parameters:
        - $ref: '#/parameters/channelCatalogIdParameter'
      responses:
        200:
          description: Channel catalog category mappings
          schema:
            $ref: '#/definitions/channelCatalogCategoryMappings'
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'


  '/{channelCatalogId}/categoryMappings/map':
    post:
      tags:
      - Category Mappings
      summary: Map channel catalog category
      operationId: MapChannelCatalogCategory
      parameters:
        - $ref: '#/parameters/channelCatalogIdParameter'
        - name: request
          in: body
          required: true
          schema:
            $ref: '#/definitions/mapCategoryRequest'
      responses:
        204:
          description: Channel catalog category mapped
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'
          
  '/{channelCatalogId}/categoryMappings/unmap':
    post:
      tags:
      - Category Mappings
      summary: Unmap channel catalog category
      operationId: UnmapChannelCatalogCategory
      parameters:
        - $ref: '#/parameters/channelCatalogIdParameter'
        - name: request
          in: body
          required: true
          schema:
            $ref: '#/definitions/unmapCategoryRequest'
      responses:
        204:
          description: Channel catalog category unmapped
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'

  '/exclusionFilterOperators':
    get:
      tags:
      - Exclusion Filters
      summary: Get channel catalog exclusion filter operators
      operationId: GetChannelCatalogExclusionFilterOperators
      responses:
        200:
          description: Channel catalog exclusion filter operator list
          schema:
            type: array
            items:
              $ref: '#/definitions/exclusionFilterOperator'
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'

  '/{channelCatalogId}/exclusionFilters':
    put:
      tags:
      - Exclusion Filters
      summary: Configure channel catalog exclusion filters
      operationId: ConfigureChannelCatalogExclusionFilters
      parameters:
        - $ref: '#/parameters/channelCatalogIdParameter'
        - name: request
          in: body
          required: true
          schema:
            $ref: '#/definitions/exclusionFilters'
      responses:
        204:
          description: Channel catalog exclusion filter list configured

        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'


  '/{channelCatalogId}/products':
    post:
      tags:
      - Products
      summary: Get channel catalog product information list
      operationId: GetChannelCatalogProductInfoList
      parameters:
        - $ref: '#/parameters/channelCatalogIdParameter'
        - name: request
          in: body
          description: The channel catalog product list filter
          schema:
            $ref: '#/definitions/getChannelCatalogProductInfoListRequest'
      responses:
        200:
          description: Channel catalog product information
          schema:
            $ref: '#/definitions/channelCatalogProductInfoList'
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'



  '/products/{productId}':
    post:
      tags:
      - Products
      summary: Get channel catalog products related to these channel catalogs 
      operationId: GetChannelCatalogProductByChannelCatalog
      parameters:
        - $ref: '#/parameters/productIdParameter'
        - name: request
          in: body
          schema:
            $ref: '#/definitions/channelCatalogProductByChannelCatalogRequest'
              
      responses:
        200:
          description: The channel catalog product by channel catalog
          schema:
            $ref: '#/definitions/channelCatalogProductByChannelCatalogResponse'
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'
  
  

  '/{channelCatalogId}/products/{productId}':
    get:
      tags:
      - Products
      summary: Get channel catalog product information
      operationId: GetChannelCatalogProductInfo
      parameters:
        - $ref: '#/parameters/channelCatalogIdParameter'
        - $ref: '#/parameters/productIdParameter'
      responses:
        200:
          description: Channel catalog product information
          schema:
            $ref: '#/definitions/channelCatalogProductInfo'
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'


  '/{channelCatalogId}/products/{productId}/overrides':
    put:
      tags:
      - Products Overrides
      summary: Override channel catalog product values
      operationId: OverrideChannelCatalogProductOverrides
      parameters:
        - $ref: '#/parameters/channelCatalogIdParameter'
        - $ref: '#/parameters/productIdParameter'
        - name: request
          in: body
          required: true
          schema:
            $ref: '#/definitions/productOverrides'
      responses:
        204:
          description: Channel catalog product overriden
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'

  '/{channelCatalogId}/products/{productId}/overrides/{channelColumnId}':
    delete:
      tags:
      - Products Overrides
      summary: Delete a specific channel catalog product value override
      operationId: DeleteChannelCatalogProductValueOverride
      parameters:
        - $ref: '#/parameters/channelCatalogIdParameter'
        - $ref: '#/parameters/productIdParameter'
        - name: channelColumnId
          description: The channel column identifier
          in: path
          type: string
          format: guid
          required: true
          x-example: '8a76f06a-fefc-4c0d-bcfe-b210f1482977'
      responses:
        204:
          description: Channel catalog product value override deleted
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'


  '/{channelCatalogId}/products/{productId}/disable':
    post:
      tags:
      - Products Optimisation
      summary: Disable channel catalog product
      operationId: DisableChannelCatalogProduct
      description: |
        By default a all your catalog products are exposed to the channel.
        You can disable a product by using this operation.
        /!\ In case of massive optimisation we recommand you to use the analytics api
      parameters:
        - $ref: '#/parameters/channelCatalogIdParameter'
        - $ref: '#/parameters/productIdParameter'
      responses:
        204:
          description: Channel catalog product disabled
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'

  '/{channelCatalogId}/products/{productId}/reenable':
    post:
      tags:
      - Products Optimisation
      summary: Reenable channel catalog product
      description: |
        By default a all your catalog products are exposed to the channel.
        You can reenable a product by using this operation.
        /!\ In case of massive optimisation we recommand you to use the analytics api
      operationId: ReenableChannelCatalogProduct
      parameters:
        - $ref: '#/parameters/channelCatalogIdParameter'
        - $ref: '#/parameters/productIdParameter'
        
      responses:
        204:
          description: Channel catalog product reenabled
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'


  '/{channelCatalogId}/exportations/cache':
    get:
      tags:
      - Exportations
      summary: Get the exportation cache information
      operationId: GetChannelCatalogExportationCacheInfo
      parameters:
        - $ref: '#/parameters/channelCatalogIdParameter'
      responses:
        200:
          description: Channel catalog exportation cache information
          schema:
            $ref: '#/definitions/channelCatalogExportCacheInfoResponse'
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'
    delete:
      tags:
      - Exportations
      summary: Delete the exportation cache 
      operationId: DeleteChannelCatalogExportationCache
      parameters:
        - $ref: '#/parameters/channelCatalogIdParameter'
      responses:
        204:
          description: Channel catalog exportation cache deleted
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'


  '/{channelCatalogId}/exportations/history':
    get:
      tags:
      - Exportations
      summary: Get the exportation history
      operationId: GetChannelCatalogExportationHistory
      parameters:
        - $ref: '#/parameters/channelCatalogIdParameter'
      responses:
        200:
          description: Channel catalog exportation history
          schema:
            $ref: '#/definitions/channelCatalogExportationHistory'
        default:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/responses/GeneralError'
            




definitions:

  links.GetChannelCatalogExportationCacheInfoLink:
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.Link3'
    - example:
        href: /v2/user/channelCatalogs/6d6b04de-406b-4539-8e7e-bf3e8da5dfb0/exportations/cache
        method: GET

  links.GetChannelCatalogExportationHistoryLink:
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.Link3'
    - example:
        href: /v2/user/channelCatalogs/6d6b04de-406b-4539-8e7e-bf3e8da5dfb0/exportations/history
        method: GET


  links.DeleteChannelCatalogExportationCacheLink:
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.Link3'
    - example:
        href: /v2/user/channelCatalogs/6d6b04de-406b-4539-8e7e-bf3e8da5dfb0/exportations/cache
        method: DELETE

  channelCatalogExportCacheInfoResponse:
    type: object
    required:
    - cacheInfo
    - links
    properties:
      cacheInfo:
        $ref: '#/definitions/channelCatalogExportCacheInfo'
      links:
        $ref: '#/definitions/channelCatalogExportCacheInfoResponseLinks'
    
    
    
  channelCatalogExportCacheInfoResponseLinks:
    type: object
    required:
    - self
    - delete
    properties:
      self:
        $ref: '#/definitions/links.GetChannelCatalogExportationCacheInfoLink'
      delete:
        $ref: '#/definitions/links.DeleteChannelCatalogExportationCacheLink'
        
    
  channelCatalogExportCacheInfo:
    type: object
    required:
    - status
    properties:
      status:
        type: string
        enum:
        - ReadyForGeneration
        example: ReadyForGeneration
        


  channelCatalogExportationHistoryLinks:
    type: object
    properties:
      self:
        $ref: '#/definitions/links.GetChannelCatalogExportationHistoryLink'
      
  channelCatalogExportationHistory:
    type: object
    required:
    - links
    - exportations
    properties:
# [Style Validator (32a521e3-c4d9-43e7-9446-13c5fbcd028a) : All model properties must have examples]: Field 'example' required in 'properties'
      exportations:
        type: array
        items:
          $ref: '#/definitions/channelCatalogExportationReporting'
      links:
        $ref: '#/definitions/channelCatalogExportationHistoryLinks'


  channelCatalogExportationReporting:
    type: object
    required:
    - exportationUtcDate
    - clientIpAddress
    - clientUserAgent
    properties:
      exportationUtcDate:
        description: The exportation UTC date
        type: string
        format: date-time
        example: '2014-08-25T07:32:31.584Z'
      exportationDuration:
        description: |
          The exportation duration. \
          '00:01:00' measn 1 minute.
        type: string
        pattern: (00:1[5-9])|(00:[2-5][0-9])|(0[1-9]:[0-5][0-9])|(1[0-9]:[0-5][0-9])|(2[0-3]:[0-5][0-9])
        example: '00:01:00'
      cacheStatus:
        description: The cache status during the exportation
        type: string
        enum:
        - Error
        - Available
        - GeneratedManually
        example: Available
      exportedProductCount:
        type: integer
        format: int32
        description: The exportated product count during this exportation
        example: 10142
      clientIpAddress:
        type: string
        description: The IP address of the client who requests this exportation
        example: 42.101.42.101
      clientUserAgent:
        type: string
        description: The http header User-Agent sent by the client who requests this operation
        example: 'Wget/1.13.4 (linux-gnu)'
    


  channelCatalogList:
    type: object
    properties:
# [Style Validator (32a521e3-c4d9-43e7-9446-13c5fbcd028a) : All model properties must have examples]: Field 'example' required in 'properties'
      links:
        description: Indicates how to create a channel catalog and how to get the channel catalog list 
        type: array
        items:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.Link2'
# [Style Validator (32a521e3-c4d9-43e7-9446-13c5fbcd028a) : All model properties must have examples]: Field 'example' required in 'properties'
      channelCatalogs:
        type: array
        items:
          $ref: '#/definitions/channelCatalog'
  


  createChannelCatalogRequest:
    type: object
    required:
    - channelId
    - storeId
    properties:
      channelId:
        $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.ChannelId'
      storeId:
        $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.StoreId'  


  generalSettings:
    description: Represents the general settings of your channel catalog 
    type: object
    required:
    - acceptToPublishInfo
    - useBid
    - noCategoryMapping
    - doNotExportOutOfStockProducts
    - activeBeezUPTracking
    properties:
      acceptToPublishInfo:
        description: If true then you authorize disclosure of my statistics generated from clicks and sales
        type: boolean
        example: true
      useBid:
        description: Activate bidding for this channel
        type: boolean
        example: false
      noCategoryMapping:
        description: Indicates that the channel authorize you to do not map your categories with their categories 
        type: boolean
        example: false
      doNotExportOutOfStockProducts:
        description: |
          Do not export "out of stock" products. Note: this option is not taken into account by the counter.
        type: boolean
        example: true
      activeBeezUPTracking:
        description: Activate BeezUP tracking for my statistics (checked by default)
        type: boolean
        default: true
        example: true
        

  costType:
    description: |
      CPC means cost per click.
      CPA means cost per action.
      You can have CPC/CPA with a global cost value.
      You can have CPC/CPA by category the cost value MUST be null
      You can have global fixed price.
    type: string
    enum:
    - CPC_Global 
    - CPA_Global
    - CPC_ByCategory 
    - CPA_ByCategory
    - Fixed_Global
    example: Fixed_Global

  
  costSettings:
    description: Depending to the cost type you will have to define a cost value.
    type: object
    required:
    - costType
    properties:
      costType:
        $ref: '#/definitions/costType'
      globalCostValue:
        description: In case of global cost type, you have to indicate the cost value.
        type: number
        format: decimal
        example: 10.21

  
  unmapCategoryRequest:
    description: The request message to unmap a catalog category path to a channel category path
    type: object
    required:
    - catalogCategoryPath
    properties:
      catalogCategoryPath:
        $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.CatalogCategoryPath'
    
  mapCategoryRequest:
    description: The request message to make a mapping between catalog category path and a channel category path
    type: object
    required:
    - overrideSubCategoryMappings
    - autoMapNewSubCategories
    - channelCatalogCategoryMapping
    properties:
      overrideSubCategoryMappings:
        description: Great feature! In case of mapping to parent channel category, you can ask to override the mapping of all sub channel category to this catalog category path
        type: boolean
        example: true
      autoMapNewSubCategories:
        description: Great feature! In case of mapping to parent catalog category, you can ask to automatically map new sub catalog category in the next importation to this channel category path. 
        type: boolean
        example: true
      channelCatalogCategoryMapping:
        $ref: '#/definitions/channelCatalogCategoryMapping'


  channelCatalogCategoryMappings:
    type: object
    required:
    - links
    - channelCatalogCategoryMappings
    properties:
      links:
        type: array
        items: 
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.Link2'
        example:
        - rel: mapCategory
          operationId: MapChannelCatalogCategory
          href: /v2/user/channelCatalogs/{channelCatalogId}/categoryMappings/map
          parameters:
          - name: channelCatalogId
            type: string
            required: true
            in: path
            value: '6d6b04de-406b-4539-8e7e-bf3e8da5dfb0'

# [Style Validator (32a521e3-c4d9-43e7-9446-13c5fbcd028a) : All model properties must have examples]: Field 'example' required in 'properties'
      channelCatalogCategoryMappings:
        type: array
        items:
          $ref: '#/definitions/channelCatalogCategoryMappingInfo'

  channelCatalogCategoryMappingInfo:
    allOf:
    - $ref: '#/definitions/channelCatalogCategoryMapping'
    - type: object
      required:
      - catalogCategoryPath
      - channelCategoryPath
      - links
      properties:
        links:
          type: array
          items: 
            $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.Link2'
          example:
          - rel: unmapCategory
            operationId: MapChannelCatalogCategory
            href: /v2/user/channelCatalogs/{channelCatalogId}/categoryMappings/unmap
            parameters:
            - name: channelCatalogId
              type: string
              required: true
              in: path
              value: '6d6b04de-406b-4539-8e7e-bf3e8da5dfb0'
            - name: request
              in: path
              type: object
              required: true
              value:
                catalogCategoryPath:
                - Vêtements
                - Femmes
                - Chaussures
                
                
              

    
  channelCatalogCategoryMapping:
    type: object
    description: |
      Represent a mapping between a catalog category path and a channel category path. 
      The cost on this mapping can be applied.
    required:
    - catalogCategoryPath
    - channelCategoryPath
    properties:
      catalogCategoryPath:
        $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.CatalogCategoryPath'
      channelCategoryPath:
        $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.ChannelCategoryPath'
      costValue:
        description: In case of CPC_ByCategory or CPA_ByCategory cost type, you have to indicate the cost value.
        type: number
        format: decimal
        example: 10.21

  columnMappingWithName:
    allOf:
    - $ref: '#/definitions/columnMapping'
    - type: object
      properties:
        channelColumnName:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.ChannelColumnName'
        channelBeezUPColumnName:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.BeezUPColumnName'
        catalogColumnName:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.CatalogColumnUserName'
        catalogBeezUPColumnName:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.BeezUPColumnName'
          
          

  columnMapping:
    description: Represent a mapping between a channel column considering channel category mapping and a catalog column 
    type: object
    properties:
      channelColumnId:
        $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.ChannelColumnId'
      channelCategoryPath:
        $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.ChannelCategoryPath'
      catalogColumnId:
        $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.CatalogColumnId'



  upgradeOfferRequired:
    description: The message contains the offer identifier required to execute this operation
    type: object
    required:
    - offerId
    properties:
      offerId:
        type: integer
        format: int32
        description: The offer identifier required
        example: 9


  columnMappingWithNameList:
    description: The column mapping list between a channel and a catalog 
    type: array
    items:
      $ref: '#/definitions/columnMappingWithName'

  columnMappingList:
    description: The column mapping list between a channel and a catalog 
    type: array
    items:
      $ref: '#/definitions/columnMapping'


  channelCatalogState:
    type: object
    description: Channel Catalog State
    required:
    - exportedProductCount
    - columnMappingStatus
    - categoryMappingState
    - apiSettingStatus
    properties:
      exportedProductCount:
        type: integer
        format: int32
        example: 101
      columnMappingStatus:
        $ref: '#/definitions/columnMappingStatus'
      categoryMappingState:
        $ref: '#/definitions/categoryMappingState'
      apiSettingStatus:
        $ref: '#/definitions/apiSettingStatus'
      

  columnMappingStatus:
    type: string
    enum:
    - warning
    - success
    - failed
    example: success
    
  categoryMappingState:
    description: The category mapping state of the channel catalog
    type: object
    properties:
      status:
        $ref: '#/definitions/categoryMappingStatus'
      uncategorizedProductCount:
        type: integer
        format: int32
        description: Indicates the uncategorized product count
        example: 101
      categorizedWithoutCostProductCount:
        type: integer
        format: int32
        description: Indicates the categorized product count without cost defined on the category
        example: 42
      
        
  categoryMappingStatus:
    type: string
    enum:
    - warning
    - success
    - failed
    example: success
    
  apiSettingStatus:
    type: string
    enum:
    - warning
    - success
    - failed
    example: success
      

  channelCatalog:
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.ChannelBasicInfo'
    - type: object
      description: The channel catalog
      required:
      - channelCatalogId
      - channelId
      - channelName
      - channelImageUrl
      - types
      - storeId
      - enabled
      - state
      - links
      - generalSettings
      - costSettings
      - isMarketplace
      - productCount
      properties:
# [Style Validator (32a521e3-c4d9-43e7-9446-13c5fbcd028a) : All model properties must have examples]: Field 'example' required in 'properties'
        productCount:
          type: integer
          format: int32
          description: The product count exported considering category mapping. Not all filters have been applied.
        enabled:
          type: boolean
          description: Indicates if the channel catalog is active
          example: true
        isMarketplace:
          type: boolean
          description: Indicates if this channel catalog is related to a marketplace
          example: true
        channelCatalogId:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.ChannelCatalogId'
        storeId:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.StoreId'
        generalSettings:
          $ref: '#/definitions/generalSettings'
        costSettings:
          $ref: '#/definitions/costSettings'
        columnMappings:
          $ref: '#/definitions/columnMappingWithNameList'
        exclusionFilters:
          $ref: '#/definitions/exclusionFilters'
        
        exportUrl:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.HttpUrl'
        
        state:
          $ref: '#/definitions/channelCatalogState'
          
        types:
          description: The channel type list related to the channel
          type: array
          items:
            type: string
          example:
          - Marketplace

        
        links:
          description: Indicates the actions you can do on a channel catalog
          type: array
          items:
            $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.Link2'
          example:
          - rel: categoryMappings
            operationId: GetChannelCatalogCategoyMappings
            href: /v2/user/channelCatalogs/{channelCatalogId}/categoryMappings
            method: GET
            parameters:
            - name: channelCatalogId
              type: string
              required: true
              in: path
              value: '6d6b04de-406b-4539-8e7e-bf3e8da5dfb0'
          - rel: delete
            operationId: DeleteChannelCatalog
            href: /v2/user/channelCatalogs/{channelCatalogId}
            method: DELETE
            parameters:
            - name: channelCatalogId
              type: string
              required: true
              in: path
              value: '6d6b04de-406b-4539-8e7e-bf3e8da5dfb0'
          - rel: disable
            operationId: DisableChannelCatalog
            href: /v2/user/channelCatalogs/{channelCatalogId}/disable
            method: POST
            parameters:
            - name: channelCatalogId
              type: string
              required: true
              in: path
              value: '6d6b04de-406b-4539-8e7e-bf3e8da5dfb0'
            
          - rel: exportation
            operationId: GetChannelCatalogExportationCacheInfo
            href: /v2/user/channelCatalogs/{channelCatalogId}/exportations/cache
            method: GET
            parameters:
            - name: channelCatalogId
              type: string
              required: true
              in: path
              value: '6d6b04de-406b-4539-8e7e-bf3e8da5dfb0'
    
          - rel: exportationHistory
            operationId: GetChannelCatalogExportationHistory
            href: /v2/user/channelCatalogs/{channelCatalogId}/exportations/history
            method: GET
            parameters:
            - name: channelCatalogId
              type: string
              required: true
              in: path
              value: '6d6b04de-406b-4539-8e7e-bf3e8da5dfb0'

            

  productOverrides:
    description: The key is the channel column identifier
    type: object
    additionalProperties:
      type: string
    example:
      '8a76f06a-fefc-4c0d-bcfe-b210f1482977': '3563'
      'B7B79A0B-A8DE-54DA-964C-E2704DF3738A': 'SHBELNL56'
      '57F70E81-E4F2-5034-BC65-E1D5C48EBEDA': 'Sony bravia'
      '2A77749D-0AAB-5245-89B5-6A1A4E06DACA': 'http://www.blalbla.nl/images/cache/dldldl.jpg'
      '54B3B3CB-5CA5-5471-9DAE-5310C032059A': 'http://www.blalbla.nl/images/cache/dlmdl.jpg'
      '0EA21509-1141-57BD-B679-371BC98B2ADA': 'http://www.blalbla.nl/images/cache/ldldld.jpg'


  productOverridesWithCatalogValues:
    description: The key is the channel column identifier
    type: object
    additionalProperties:
      $ref: '#/definitions/productOverrideWithCatalogValue'
    example:
      '8a76f06a-fefc-4c0d-bcfe-b210f1482977':
        catalogValue: 'x235'
        override: '3563'
      'B7B79A0B-A8DE-54DA-964C-E2704DF3738A': 
        catalogValue: 'x_ezlSHBELNL56'
        override: 'SHBELNL56'
      '57F70E81-E4F2-5034-BC65-E1D5C48EBEDA': 
        catalogValue: 'Sony'
        override: 'Sony bravia'
      '2A77749D-0AAB-5245-89B5-6A1A4E06DACA': 
        catalogValue: 'http://www.toto.com/thing/images/cache/dldldl.jpg'
        override: 'http://www.blalbla.nl/images/cache/dldldl.jpg'
      '54B3B3CB-5CA5-5471-9DAE-5310C032059A': 
        catalogValue: 'http://www.toto.com/thing/cache/dlmdl.jpg'
        override: 'http://www.blalbla.nl/images/cache/dlmdl.jpg'
      '0EA21509-1141-57BD-B679-371BC98B2ADA': 
        catalogValue: 'http://www.toto.com/thing/images/cache/ldldld.jpg'
        override: 'http://www.blalbla.nl/images/cache/ldldld.jpg'

  productOverrideWithCatalogValue:
    type: object
    required:
    - override
    properties:
      override:
        type: string
        description: The overrided product value
        example: 'Sony bravia'
      catalogValue:
        type: string
        description: The catalog product value
        example: 'Sony'
        

  exclusionFilters:
    description: The exclusion filter list
    type: array
    items:
      $ref: '#/definitions/exclusionFilter'


  exclusionFilterName:
    type: string
    description: The exclusion filter name
    example: Exclude sony products

  

  exclusionFilter:
    description: The exclusion filter
    type: object
    required:
    - name
    - position
    - groupId
    - positionInGroup
    - channelColumnId
    - operatorName
    - enabled
    properties:
      name:
        $ref: '#/definitions/exclusionFilterName'
      position:
        type: integer
        format: int32
        description: The position of the exclusion filter
        minimum: 1
        example: 1
      groupId:
        type: string
        format: guid
        description: Indicate the filter's group. All filters in the same group means an "AND" operation in the filter group
        example: 'd9833f4b-718a-436f-bab5-89da3d21bf60'
      positionInGroup:
        type: integer
        format: int32
        description: Indicate the filter group position. This information is used for the UI purpose and must be unique in the filter group.
        minimum: 1
        example: 1
      channelColumnId:
        $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.ChannelColumnId'
      operatorName:
        $ref: '#/definitions/exclusionFilterOperatorName'
      value:
        description: The value indicate by the user when the filter operation requires it.
        type: string        
        example: 'sony'
      enabled:
        description: indicates if the filter is currently active.
        type: boolean        
        example: true
        
  exclusionFilterOperatorName:
    description: The exclusion filter operator name 
    type: string
    x-lov: ChannelCatalogExclusionFilterOperator
    example: Contains
    
    
  exclusionFilterOperatorDataType:
    description: Data type of the operator
    enum:
      - string
      - number
    type: string
    default: string
    example: string
    


  exclusionFilterOperator:
    description: The exclusion filter operator
    type: object
    properties:
      name:
        $ref: '#/definitions/exclusionFilterOperatorName'
      expectedChannelColumnDataType:
        $ref: '#/definitions/exclusionFilterOperatorDataType'
      valueRequired:
        type: boolean
        description: This operator requires a value
        example: true
      expectedValueDataType:
        $ref: '#/definitions/exclusionFilterOperatorDataType'
  
  
  getChannelCatalogProductInfoListRequest:
    type: object
    properties:
      sku:
        type: string
        description: Search by product sku. If null the filter will not be taken in account.
        example: M123
      title:
        type: string
        description: Search by product title. If null the filter will not be taken in account.
        example: Réfrigérateur
      overrided:
        type: boolean
        description: Search overrided products. If null the filter will not be taken in account.
        example: true
      disabled:
        type: boolean
        description: Search disabled products. If null the filter will not be taken in account.
        example: false
      categoryMapped:
        type: boolean
        description: Search product with category mapped with the channel. If null the filter will not be taken in account.
        example: false
      excluded:
        type: boolean
        description: Search excluded products by at least an exclusion filter. If null the filter will not be taken in account.
        example: false
      active:
        type: boolean
        description: If false, search for product absent from the current catalog. If null the filter will not be taken in account.
        example: true
  
        
  links.GetChannelCatalogProductInfoLink:
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.Link3'
  
  
  
  
  channelCatalogProductInfoList:
    description: The channel catalog product info list
    type: object
    properties:
# [Style Validator (32a521e3-c4d9-43e7-9446-13c5fbcd028a) : All model properties must have examples]: Field 'example' required in 'properties'
      links:
        type: object
        properties:
          self:
            $ref: '#/definitions/links.GetChannelCatalogProductInfoLink'
          
# [Style Validator (32a521e3-c4d9-43e7-9446-13c5fbcd028a) : All model properties must have examples]: Field 'example' required in 'properties'
      productInfos:
        type: array
        items:
          $ref: '#/definitions/channelCatalogProductInfo'
    
  channelCatalogProductInfo:
    allOf:
    - $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.ProductBasicInfo'
    - type: object
      description: The channel catalog product information
      required:
      - productId
      - overrides
      - disabled
      - categoryMapped
      - excluded
      - links
      properties:
        overrides:
          $ref: '#/definitions/productOverridesWithCatalogValues'
        disabled:
          type: boolean
          description: Indicates if the product has been disabled or not
          default: false
          example: false
        categoryMapped:
          type: boolean
          description: Indicates if the product's category has been mapped to a channel category 
          example: true
        excluded:
          type: boolean
          description: Indicates if the product has been excluded by a exclusion filter
          default: false
          example: true
        excludedBy:
          type: array
          items:
            $ref: '#/definitions/exclusionFilterName'
          example:
          - Exclude sony products
        links:
          $ref: '#/definitions/channelCatalogProductInfoLinks'

  channelCatalogProductInfoLinks:
    description: Indicates the differents actions you can do on a channel product
    type: object
    required:
    - override
    properties:
      override:
        $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.Link2'
      disable:
        $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.Link2'
      reenable:
        $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.Link2'

        


        
        
  channelCatalogProductByChannelCatalogRequest:
    type: object
    properties:
# [Style Validator (32a521e3-c4d9-43e7-9446-13c5fbcd028a) : All model properties must have examples]: Field 'example' required in 'properties'
      channelCatalogIds:
        description: The list of channel catalog identifier
        type: array
        items:
          $ref: 'https://api.swaggerhub.com/domains/BeezUP/api.beezup.com/v2#/definitions/BeezUP.Common.ChannelCatalogId'
      
  
  channelCatalogProductByChannelCatalogResponse:
    type: object
    properties:
# [Style Validator (32a521e3-c4d9-43e7-9446-13c5fbcd028a) : All model properties must have examples]: Field 'example' required in 'properties'
      channelCatalogs:
        description: The channel catalog product by channel catalog. The key is the channel catalog identifier 
        type: object
        additionalProperties:
          $ref: '#/definitions/channelCatalogProductInfo'

      
x-azure-api-id: 'V2UserChannelCatalogs'